name: 'Discord Commit Message Webhook'
description: 'Send a customizable Discord embed via webhook on each commit push, notifying users of the latest changes instantly.'
branding:
  icon: 'at-sign'
  color: 'black'
author: 'Tristan Budd'
inputs:
  webhook-url:
    description: 'Discord Webhook URL'
    required: true
  github-token:
    description: 'GitHub token for accessing commit data (ONLY REQUIRED FOR CHANGED FILES)'
    required: false
  text-content:
    description: 'Text content to send with the embed'
    required: false
  embed-title:
    description: 'Title for the embed'
    required: false
  embed-description:
    description: 'Description for the embed'
    required: false
  embed-colour:
    description: 'Embed colour in hex, e.g. #FFFFFF for white'
    required: false
    default: '#FFFFFF'
  embed-author-name:
    description: 'Author name in the embed'
    required: false
  embed-author-icon-url:
    description: 'URL of the author icon in the embed'
    required: false
  embed-author-url:
    description: 'URL of the author in the embed'
    required: false
  embed-thumbnail-url:
    description: 'URL of thumbnail image in embed'
    required: false
  embed-image-url:
    description: 'URL of image to display in embed'
    required: false
  embed-footer-text:
    description: 'Footer text in the embed'
    required: false
  embed-footer-icon-url:
    description: 'URL of the footer icon in the embed'
    required: false
  embed-footer-timestamp:
    description: 'Show timestamp in the embed footer'
    required: false
    default: 'true'
  show-commit-message:
    description: 'Show commit message in embed'
    required: false
    default: 'true'
  show-changed-files:
    description: 'Show list of changed files (Requires github-token)'
    required: false
    default: 'false'
  show-commit-branch:
    description: 'Show commit branch in embed'
    required: false
    default: 'true'
  show-commit-author:
    description: 'Show commit author in embed'
    required: false
    default: 'true'
  show-commit-link:
    description: 'Show link to commit in embed'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
