name: Send Test Discord Commit Message - Minimal

on: [push]

jobs:
  discord_notify_empty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: tristanbudd/discord-commit-github-action@master
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
